"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Gaëtan Lehmann"
email = "gaetan.lehmann@gmail.com"

[ui]
default-command = ["log", "-T", "zen"]

[colors]
"diff token" = { underline = false }
"diff removed token" = { bg = "#221313" }
"diff added token" = { bg = "#222922" }

[templates]
log = "builtin_log_compact_full_description"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[aliases]
annotate = ["file", "annotate"]
ci = ["commit"]
clone = ["git", "clone", "--colocate"]
init = ["git", "init", "--colocate"]
push = ["git", "push"]
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
up = ["util", "exec", "--", "bash", "-c", """
#!/usr/bin/env bash
set -euo pipefail
bookmark=`jj log -r 'closest_bookmark(@) & tracked_remote_bookmarks()' -T bookmarks --no-graph`
jj git fetch
jj rebase -d $bookmark
""", ""]

[revset-aliases]
branch = "trunk()::@"
br = "branch"
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

[template-aliases]
detailed = "builtin_log_detailed"
zen = '''
if(root,
separate(" ",
  format_short_change_id(self.change_id()),
    label("root", "root()"),
    self.bookmarks(),
  ) ++ "\n",
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        commit_timestamp(self).ago(),
        bookmarks,
        tags,
        working_copies,
        if(conflict, label("conflict", "conflict")),
        if(config("ui.show-cryptographic-signatures").as_boolean(),
          format_short_cryptographic_signature(signature)),
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

# override user.email if the repository is located under ~/src/vates
[[--scope]]
--when.repositories = ["~/src/vates"]
[--scope.user]
email = "gaetan.lehmann@vates.tech"
